from fpdf import FPDF
import os

class PregaCarePatientReport(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(79, 70, 229) # Indigo
        self.cell(0, 15, 'PregaCare Health Analysis Report', ln=True, align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by PregaCare AI - Page {self.page_no()}', align='C')

    def chapter_title(self, title):
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(31, 41, 55) # Slate-800
        self.cell(0, 10, title, ln=True)
        self.ln(2)
        self.set_draw_color(229, 231, 235)
        self.line(self.get_x(), self.get_y(), self.get_x() + 190, self.get_y())
        self.ln(5)

    def chapter_body(self, body):
        self.set_font('helvetica', '', 12)
        self.set_text_color(55, 65, 81) # Slate-700
        self.multi_cell(0, 7, body)
        self.ln(5)

    def stats_box(self, label, value, color=(31, 41, 55)):
        self.set_font('helvetica', 'B', 12)
        self.set_text_color(107, 114, 128) # Slate-500
        self.cell(40, 10, f"{label}:", ln=False)
        self.set_font('helvetica', 'B', 14)
        self.set_text_color(*color)
        self.cell(0, 10, str(value), ln=True)

def generate_patient_pdf(report_data, vitals, output_path):
    pdf = PregaCarePatientReport()
    pdf.add_page()
    
    # 1. Summary
    pdf.chapter_title('1. Assessment Summary')
    
    risk_color = (16, 185, 129) # Green
    if 'Mid' in report_data['risk_band']:
        risk_color = (245, 158, 11) # Orange
    elif 'High' in report_data['risk_band']:
        risk_color = (239, 68, 68) # Red
        
    pdf.stats_box('Overall Risk', report_data['risk_band'].upper(), risk_color)
    pdf.stats_box('PregaCare Index', f"{report_data['combined_score']}/100", (79, 70, 229))
    pdf.stats_box('Location', report_data['location'])
    pdf.ln(5)
    
    # 2. Vitals Analysis
    pdf.chapter_title('2. Clinical Vitals')
    for key, val in vitals.items():
        pdf.set_font('helvetica', '', 12)
        pdf.set_text_color(55, 65, 81)
        pdf.cell(50, 8, f"{key}:", ln=False)
        pdf.set_font('helvetica', 'B', 12)
        pdf.cell(0, 8, str(val), ln=True)
    pdf.ln(5)
    
    # 3. Insights
    pdf.chapter_title('3. AI Insights & Action Plan')
    pdf.chapter_body(report_data['suggested_action'])
    
    pdf.chapter_body(
        "This report was generated using PregaCare's proprietary stacking ensemble model "
        "and regional infrastructure analysis based on NFHS-5 data. "
        "Please consult a medical professional for a detailed clinical diagnosis."
    )
    
    pdf.output(output_path)
    return output_path
